public/index.html, src/App.css, src/App.tsx, src/index.css
=> add font and main page

src/App.css, src/App.tsx, src/Header/index.module.css, src/components/Input/Input.tsx, src/components/Input/index.module.css, src/components/MainPage/MainPage.tsx, src/components/MainPage/index.module.css
создал инпут, вложив его в лейбл +враппер. инпут не встает в 100% label -- пришлось выравнивать вручную (96%)
https://github.com/diekuche/gutenberg/issues/3#issue-1365679426
=> add input component

src/components/Button/Button.module.css, src/components/Button/Button.tsx, src/components/ButtonAddToken/ButtonAddToken.module.css, src/components/ButtonAddToken/ButtonAddToken.tsx, src/components/ButtonSend/ButtonSend.module.css, src/components/ButtonSend/ButtonSend.tsx, src/components/MainPage/MainPage.tsx
https://prnt.sc/60mlO4UnSO4v - кнопка
https://prnt.sc/LEsYjc232kK9 - состояние Active
=> button active and hover

src/components/Button/Button.module.css, src/components/Button/Button.tsx, src/components/Button/ButtonAddToken.tsx, src/components/Button/ButtonSend.tsx, src/components/Form/Form.tsx, src/components/ManageTokens/ManageTok.tsx
сделать из всех кнопок одну, добавил classnames и стринги size и color, лишние кнопки не удалял
https://github.com/diekuche/gutenberg/issues/20#issue-1372364476
=> add multibutton

src/components/Collapsible/Collapsible.tsx, src/components/Form/Form.tsx, src/components/Form/index.module.css, src/components/Tabs/Tabs.module.css, src/components/Tabs/Tabs.tsx
=> add active tab

src/components/MainPage/MainPage.tsx, src/components/NFT/NFT.module.css, src/components/NFT/NFT.tsx
Верста
Макет
Высоту/ширину задал в размерах, так как думаю поле будет в дальнейшем наполняться и после наполнения эти размеры уберутся.
=> cooming soon

src/components/Contracts/Contract.module.css, src/components/Contracts/Contract.tsx, src/components/ManageTokens/ManageTok.module.css
добавить возможность отправлять токены
=> add send func

src/components/BootSender/BootSender.tsx, src/components/Token/Token.tsx
balance update
tested with 2 accs, also condition added if have no boot 
https://github.com/diekuche/gutenberg/issues/61#issue-1454596517
=> balance updates

src/App.css, src/components/Input/Input.tsx, src/components/ManageTokens/ManageTok.module.css
=> fix height

src/components/BootSender/BootSender.module.css, src/components/BootSender/BootSender.tsx, src/components/ManageTokens/ManageTok.module.css, src/components/ManageTokens/ManageTok.tsx, src/components/Token/Token.module.css, src/components/Token/Token.tsx
=> Addtokenfixing

src/components/ManageTokens/ManageTok.tsx, src/components/Wallet/Wallet.tsx
update wallet address +fixing first letter deleting
=> Walletupdater

src/components/Form/Form.tsx, src/components/MainPage/MainPage.tsx, src/components/ManageTokens/ManageTok.tsx, src/components/Token/Token.module.css, src/utils/wallet.ts
auto-adding contracts after submit
=> Fetchingcontracts

src/components/Input/index.module.css
=> color input

src/components/BootSender/BootSender.module.css, src/components/Button/Button.module.css
delet white field inise input
delet opacity Button
=> design opacity/outline

src/App.tsx, src/assets/download.svg, src/components/HeaderSpoiler/index.module.css, src/components/newButton/newButton.module.css, src/components/newButton/newButton.tsx
layout - 
Figma - https://www.figma.com/file/xQoRnWDlMtEUSG7WcKqlzB/GUT!?node-id=245%3A1934&t=jlcfUwxjW19Nu2t8-0
created buttons at http://localhost:3000/newBT
=> redisignButtons84

src/components/BasicWindow/BasicWindow.tsx, src/components/HeaderSpoiler/HeaderSpoiler.tsx, src/components/HeaderSpoiler/index.module.css, src/components/ManageTok/ManageTok.module.css, src/components/ManageTok/ManageTok.tsx
=> issuenumber93

src/components/MainPage/MainPage.tsx, src/components/MainPage/index.module.css
=> fix header in create

README.md
=> add twitter

src/components/Header/Header.tsx
=> hided junotest

.github/workflows/main.yml
Добавлен новый github action для деплоя
=> changed github action
